minimum_pre_commit_version: 3.2.0
default_install_hook_types: [pre-commit]

repos:
  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort
        stages: [pre-commit, manual]
  - repo: https://github.com/psf/black
    rev: 23.10.0
    hooks:
      - id: black
        stages: [pre-commit, manual]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: refs/tags/v4.5.0
    hooks:
      - id: trailing-whitespace
        stages: [pre-commit, manual]
      - id: end-of-file-fixer
        stages: [pre-commit, manual]
  - repo: https://github.com/executablebooks/mdformat
    rev: refs/tags/0.7.17
    hooks:
      - id: mdformat
        stages: [pre-commit, manual]
        # Same width that black uses by default.
        args: [--wrap=88, --number]
